# Generated by Django 6.0.2 on 2026-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('vacancy', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
